### ISSUE TITLE
Package spec needs to be rewritten, or hosted at ankida

### ISSUE THREAD

**Issue by ghitchens** [jozsefsallai/go-peekalink#1]
I will admit to being new to go, so I'm maybe missing something.    

This looks like a very cool package, but not usable due to a broken package path.
It looks like the code is all setup for this to be hosted at github/ankida/go-peekalink but there is no repository there. 

The README in step 1 says to install via `go get github.com/ankida/go-peekalink`, but that repository doesn't exist.   The code package declarations are all setup to use the package at ankida instead also. 

There might be a way to let go alias this package, but as someone relatively new to go I couldn't get it to work, because even though I can alias the entire package as "peekalink", the files all reference the ankida  repo.

If you intend to continue this package at jozsefsallai I would be happy to submit a PR to the README and files to fix the broken package paths.

**Comment by jozsefsallai** [comment]
Hello!

The original plan was to move the repo to the Ankida organization, but we had to shift our attention to other things. We will eventually move the repo, but as a temporary workaround, I have changed the module path and tagged a release so the package can be fetched and installed now.

Let me know if you can install the package now!

**Comment by ghitchens** [comment]
Yes, it can be installed now and the docs are now readable at https://pkg.go.dev/github.com/jozsefsallai/go-peekalink
Appreciate the fast response.
